### ISSUE TITLE
Start Hook

### ISSUE THREAD

**Issue by offizium-berndstorath** [nitrojs/nitro#2663]
### Describe the feature

There is a hook 'close' that runs when the server stops.
I need a way to run something when the server starts.
I am using nuxt

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by rafazafar** [comment]
Hi there @offizium-berndstorath. Could you describe your use case more?
Would nitro plugins work for you, since they are ran in order on start? 
https://nitro.unjs.io/guide/plugins

**Comment by sandros94** [comment]
Here's my use-case for a `start` hook:

Nitro/Nuxt project is containerized and depends on two env vars, a private and public PEM strings. I cannot use them as they are, because they need to be converted to proper keys first, but I also need to access them project wide via runtime config.

The only current solution is to store the PEMs and elaborate them at build time, which means they get exposed in the distributed container image, but ideally I would like a `start` hook to convert those PEMs as the project is booting up.

Another use-case I can think off is using this hook to check if the related DB for that project requires to run a schema migration.

Yes, ofc, improper use of this hook would lead to increased overhead, especially in serverless environments.
