### ISSUE TITLE
Upgrade `@vercel/nft` to 0.27.4 to include ESM `module.register` hooks

### ISSUE THREAD

**Issue by s1gr1d** [nitrojs/nitro#2703]
### Environment

ESM

### Reproduction

Link: https://github.com/s1gr1d/nitro-sentry-iitm

This is how import-in-the-middle (IITM) looks like in `.output/server/node_modules`:
| Without resolution (uses @vercel/nft 0.26.x) | With @vercel/nft package resolution to 0.27.4 |
| -------- | ------- |
|   ![image](https://github.com/user-attachments/assets/447abe30-e36c-424a-b906-ebb36ea135f0) | ![image](https://github.com/user-attachments/assets/a26497d4-1820-48cc-b44d-af4cffde33c3)  |

### Describe the bug

Previous versions of @vercel/nft do not include ESM `module.register` hooks so the `@opentelemetry/instrumentation/hook.mjs` is not included, which leads to errors when starting the server if opentelemetry or packages that depend on it (like Sentry) are used.

---

`@vercel/nft` released a new version with the fix, but as it is still a `0` major version, the caret (`^`) does not work like usual. With `0` major versions, only the patch is automatically updated, but not the minor ([npm source](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004)). 

The current release of nitro depends on `^0.26.5` and the [fix is included](https://github.com/vercel/nft/pull/429) in `0.27.4` (another minor version). 

It would be awesome to release a new nitro version (minor or patch), which includes this `@vercel/nft` minor version upgrade 🙌 

### Additional context

Issue Reference:
- https://github.com/vercel/nft/issues/428
- https://github.com/getsentry/sentry-javascript/issues/12603 (netlify-related, but this uses nft as well) - includes a reproduction

**Comment by pi0** [comment]
We have already upgraded to `0.27` range in v2/main branches but since v2 branch has some risky changes that require more ecosystem testing, unfortunately, there is no immediate release planned.

In the meantime, it is possible to use [nightly release channel](https://nitro.unjs.io/guide/nightly) to receive the update.

**Comment by pi0** [comment]
We can... Can you please help to make a minimal nitro reproduction for the issue with open telemetry dependency? I remember last time there were more issues specially on nodeless (edge) platforms this way at least we can make sure this releases fully solves the problem.

**Comment by andreiborza** [comment]
Hi @pi0, any decisions on this? This also holds up otel instrumentation for vinxi for example.

**Comment by pi0** [comment]
Thanks for reproduction @s1gr1d it helped me to understand the better of usage.

@andreiborza We are working on the v2 branch to be stable (we also already asked both Nuxt and solid/vinxi teams since last week to review the nightly channel) as soon as we are sure of stability will issue a new release, I hope (but don't promise) by early next week at latest for it to happen.

My understanding is that `import-in-the-middle` is an experimental feature (and it is for Node.js targets only). In the meantime (while I fully understand the inconvenience) you can offer users to opt into the nightly channel or manually add the resolution of vercel/nft.

On a relevant topic, if you are interested I would love to have better support of Sentry for Nitro (long-time user!), i will contact you if you are intrested.

**Comment by pi0** [comment]
Sounds exciting. I wouldn't find any contact in X. Would you mind to drop me a DM in discord (`@pi0`) or X (`@_pi0_`)? 🙏🏼

**Comment by cjpearson** [comment]
We've been using a manual OpenTelemetry instrumentation for our projects and the idea of having an officially supported version is exciting! 

Have you given any thought to supporting [Native Instrumentation](https://opentelemetry.io/docs/languages/js/libraries/#use-natively-instrumented-libraries) within the Nitro package itself? (Similar to NextJS) With an external package it can be difficult to inject the necessary code at the right points. For example, in our instrumentation package we have to use a nitro plugin where we get a handle on the h3 app and patch the nitro router to wrap each request in a handle. It works, but as with all code that depends on internals there is the risk of future breakage.

https://opentelemetry.io/docs/concepts/instrumentation/libraries/

**Comment by pi0** [comment]
@cjpearson Actually yes one of the reasons I am thinking of nitro-native support is to have a cross-platform instrument. I don't prefer the complexity of open telemetry Node.js SDK either.

**Comment by cjpearson** [comment]
Oh cool. Are you open to PRs in this direction?

**Comment by DeVoresyah** [comment]
Hi, I'm using Nuxt 3 and already add resolutions for @vercel/nft but still didn't work. Here's my package version:
```
"nuxt": "^3.9.0",
```

**Comment by pi0** [comment]
[2.10](https://github.com/nitrojs/nitro/releases/tag/v2.10.0) is released with vercel/nft dependency update.

otel support requires more works.

**Comment by 5knnbdwm** [comment]
> [2.10](https://github.com/nitrojs/nitro/releases/tag/v2.10.0) is released with vercel/nft dependency update.
> 
> otel support requires more works.

@pi0 any updates on otel

**Comment by pi0** [comment]
We are working with sentry team to leverage Node.js built-in tracing channel in Nitro v3 (already landed in srvx and h3 v2). This means there will be no need of custom instruments and tracing natively working.

**Comment by 5knnbdwm** [comment]
Okay cool. Cant wait.
