### ISSUE TITLE
useNitroApp() not work

### ISSUE THREAD

**Issue by Makkalay** [nitrojs/nitro#2958]
### Environment

latest

### Reproduction

// import "#nitro-internal-pollyfills";
import { useNitroApp } from "nitropack/runtime";

const nitroApp = useNitroApp();

### Describe the bug

Need something like createApp from h3 but to get nitro app with router hooks and other?

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './runtime' is not defined by "exports" in package.json

**Comment by pi0** [comment]
Works in latest 2.10.4: https://stackblitz.com/edit/github-weasgzp4?file=server%2Froutes%2Findex.ts

(feel free to fork and edit to reproduce differently and please consider always opening bug reports with a runnable reproduction)

**Comment by Makkalay** [comment]
@pi0 in your example it work because is a nitro app what is started with  "build": "nitro build" or   "dev": "nitro dev" it think, but i need a simply ts app what run like any other

**Comment by Makkalay** [comment]
Some other framework I start and in it I want to initiate an instance of nitroApp, for h3 I can do app = createApp() or h3App or what is it.

**Comment by pi0** [comment]
`useNitroApp()` and other nitro utils are futures that work in a nitro build/runtime environment only. (h3 can be used externally)

If you are making an external/shared util that conditionally might need nitro app instance, since we use standard [unctx](https://unctx.unjs.io), you can access it: 

```js
import { AsyncLocalStorage } from "node:async_hooks";
import { getContext } from "unctx";

export const nitroAsyncContext = getContext("nitro-app", {
  asyncContext: true,
  AsyncLocalStorage
});
```

This is not a bug but the purpose of this composable. If you have any further questions please feel free to use [discussions](https://github.com/nitrojs/nitro/discussions) and also explain more what exactly you want to do.
